services:
  - type: web
    name: waste-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn new_waste_management.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
