# Generated by Django 5.2.1 on 2025-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tutorial_link',
            field=models.URLField(blank=True, help_text='YouTube link for complex processes', max_length=500, null=True),
        ),
    ]
