# Generated by Django 5.2.1 on 2025-05-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpingreport',
            name='district',
            field=models.CharField(choices=[('Kampala', 'Kampala'), ('Wakiso', 'Wakiso'), ('Masindi', 'Masindi'), ('Kasese', 'Kasese'), ('Iganga', 'Iganga'), ('Bushenyi', 'Bushenyi'), ('Gulu', 'Gulu'), ('Lira', 'Lira'), ('Mbarara', 'Mbarara'), ('Jinja', 'Jinja'), ('Mbale', 'Mbale'), ('Arua', 'Arua'), ('Soroti', 'Soroti'), ('Fort Portal', 'Fort Portal'), ('Hoima', 'Hoima'), ('Masaka', 'Masaka'), ('Mukono', 'Mukono'), ('Nebbi', 'Nebbi'), ('Tororo', 'Tororo'), ('Kabale', 'Kabale'), ('Mityana', 'Mityana'), ('Adjumani', 'Adjumani'), ('Pallisa', 'Pallisa'), ('Kumi', 'Kumi'), ('Bundibugyo', 'Bundibugyo')], default='Kampala', max_length=50),
        ),
        migrations.AlterField(
            model_name='dumpingreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
