# Generated by Django 5.2.1 on 2025-05-28 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=20)),
                ('wrong_answer_1', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=20)),
                ('wrong_answer_2', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=20)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
