# Generated by Django 5.2.1 on 2025-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastelisting',
            options={},
        ),
        migrations.RemoveField(
            model_name='wastelisting',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='wastelisting',
            name='collection_date',
        ),
        migrations.AlterField(
            model_name='wastelisting',
            name='waste_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='CollectionSchedule',
        ),
    ]
