# Generated by Django 5.2.1 on 2025-05-27 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('household', 'Household'), ('business', 'Business'), ('collector', 'Collector'), ('recycler', 'Recycler')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Phone number in format: +256XXXXXXXXX', max_length=15, null=True)),
                ('accepted_waste_types', models.CharField(blank=True, help_text='Comma-separated list of accepted waste types', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
