# Generated by Django 5.2.1 on 2025-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('household', 'Household'), ('business', 'Business'), ('collector', 'Collector'), ('recycler', 'Recycler'), ('quick_access', 'Quick Access')], max_length=20, null=True),
        ),
    ]
